-- This module serves as the root of the `BourbakiLean2` library.
-- Import modules here that should be built as part of the library.
import BourbakiLean2.Basic
import BourbakiLean2.Set.Basic
import BourbakiLean2.Set.Defs
import BourbakiLean2.Set.Rel
import BourbakiLean2.Set.Operations
import BourbakiLean2.Set.Coverings
import BourbakiLean2.Set.Prod
import BourbakiLean2.Set.Partitions
import BourbakiLean2.Set.RelMisc
import BourbakiLean2.Set.Sum
import BourbakiLean2.Equivalence
import BourbakiLean2.Function.Basic
import BourbakiLean2.Function.Prod
import BourbakiLean2.Function.Rel
import BourbakiLean2.Order.Basic
import BourbakiLean2.Order.Synonyms
import BourbakiLean2.Order.Monotone
import BourbakiLean2.Order.Intervals
import BourbakiLean2.Order.Bounds
import BourbakiLean2.Order.BoundedFunctions
import BourbakiLean2.Order.MaxMin
import BourbakiLean2.Order.Sets
import BourbakiLean2.Order.GlbLub
import BourbakiLean2.Order.TotalOrder
import BourbakiLean2.Order.Quotient
import BourbakiLean2.Order.Lattice
import BourbakiLean2.Order.Cofinal
import BourbakiLean2.Order.Coverings
import BourbakiLean2.Order.Directed
import BourbakiLean2.Order.Hom
import BourbakiLean2.Order.Inductive
import BourbakiLean2.Order.Intervals
import BourbakiLean2.Order.Sum
import BourbakiLean2.Order.WellOrder
import BourbakiLean2.Order.WellOrderIso
import BourbakiLean2.Order.Lex
import BourbakiLean2.Set.Cardinal
